app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    # url(r'^index/$',views.index,name='index'),
    # url(r'^home/$',views.home,name='home'),

    url(r'^detail/$',views.detail,name='detail'),
    url(r'^list/$',views.list,name='list'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^register/$',views.register,name='register'),
    url(r'^shoppingCar/$',views.shoppingCar,name='shoppingCar'),
    url(r'^mine/$',views.mine,name='mine'),
    url(r'^ajax/$',views.ajax,name='ajax')

]

leshangwang/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('app.urls',namespace='leshangwang'))
]

app/models.py
from django.db import models

# Create your models here.
class test(models.Model):
    name = models.CharField(max_length=80)

class User(models.Model):
    username = models.CharField(max_length=80)
    password = models.CharField(max_length=256)
    tel = models.CharField(max_length=20)

    token = models.CharField(max_length=256, default='')


class goods(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    unit = models.CharField(max_length=10)
    brand = models.CharField(max_length=50)
    img1 = models.CharField(max_length=256)
    img2 = models.CharField(max_length=256)
    img3 = models.CharField(max_length=256)
    img4 = models.CharField(max_length=256)
    img5 = models.CharField(max_length=256)
    img6 = models.CharField(max_length=256)
    img7 = models.CharField(max_length=256)
    img8 = models.CharField(max_length=256)
    img9 = models.CharField(max_length=256)
    img10 = models.CharField(max_length=256)
    trackid = models.IntegerField(default=0)

class lunbo(models.Model):
    img = models.CharField(max_length=256)
    trackid = models.IntegerField(default=0)

app/views.py
import hashlib
import random
import time
import uuid

from django.http import HttpResponse, response, JsonResponse
from django.shortcuts import render, redirect


# Create your views here.
from app.models import User, goods


def index(request):
    username = request.COOKIES.get('username')
    data = {
        'username':username,
    }
    return render(request,'index.html',context=data)

#token生成
def generate_token():
    token = str(time.time())  + str(random.random())

    # MD5
    md5 = hashlib.md5()
    md5.update(token.encode('utf-8'))
    return md5.hexdigest()

#加密
def generate_password(password):
    sha = hashlib.sha512()
    sha.update(password.encode('utf-8'))
    return sha.hexdigest()

def detail(request):
    username = request.COOKIES.get('username')
    good = goods.objects.all()
    goodslist = []
    for item in good:
        responseData = {
            'username': username,
            'id': item.id,
            'name': item.name,
            'price': item.price,
            'brand': item.brand,
            'img2': item.img2,
            'img1': item.img1,
            'img3': item.img3,
            'img4': item.img4,
            'img5': item.img5,
            'img6': item.img6,
            'img7': item.img7,
            'img8': item.img8,
            'img9': item.img9,
            'img10': item.img10,

        }
        goodslist.append(responseData)
    return render(request,'html/detail.html',context=responseData)
    # return JsonResponse({'goodslist':goodslist})

def list(request):
    username = request.COOKIES.get('username')
    good = goods.objects.all()
    for item in good:
        goodid = item.id
        data = {
            'goodid':item.id,
            'username': username,
        }

    return render(request,'html/list.html',context=data)


def login(request):
    if request.method == "GET":
        return render(request,'html/login.html')
    elif request.method == "POST":
        username = request.POST.get("username")
        password =  generate_password( request.POST.get("password") )
        print(username,password)

        users = User.objects.filter(username=username).filter(password=password)
        if users.exists():
            user = users.first()
            response = redirect('leshangwang:index')
            response.set_cookie('username', user.username)
            print(username)
            return response
        else:
            return HttpResponse('用户名或密码错误!')


def register(request):
    if request.method ==  "GET":
        return render(request,'html/register.html')
    elif request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        tel = request.POST.get('username')
        print(username,password,tel)

        #存入数据库
        try:
            user = User()
            user.username = username
            user.password = generate_password(password)
            user.tel = username
            user.save()    #
            response = redirect('leshangwang:index')
            response.set_cookie('username',username)
            return response
        except Exception as e:
            return HttpResponse('注册失败' + e)



def shoppingCar(request):
    username = request.COOKIES.get('username')
    return render(request,'html/shoppingCar.html',context={'username':username})


def logout(request):
    response = redirect('leshangwang:index')
    response.delete_cookie('username')
    return response


def mine(request):
    return render(request,'html/mine.html')


def ajax(request):
    good = goods.objects.all()
    goodslist = []
    for item in good:
        responseData = {
            'id': item.id,
            'name': item.name,
            'price': item.price,
            'brand': item.brand,
            'img2': item.img2,
            'img1': item.img1,
            'img3': item.img3,
            'img4': item.img4,
            'img5': item.img5,
            'img6': item.img6,
            'img7': item.img7,
            'img8': item.img8,
            'img9': item.img9,
            'img10': item.img10,
        }
        goodslist.append(responseData)

    print(goodslist)
    return JsonResponse({'goodslist':goodslist})

templates/html/detail.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
	</head>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset .css' %}" />
	<script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}" ></script>
	<link rel="stylesheet" href="{% static 'css/detail.css' %}" />
	<script type="text/javascript" src="{% static 'js/detail.js' %}" ></script>
	<script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}" ></script>
	<script type="text/javascript" src="{% static 'js/jquery.fly.min.js' %}" ></script>

	<script>
		$(function(){

			//获取从列表页传过来的id
			// location.search : 参数部分， 如:?id=1002&name=lisi
			var param = location.search.substring(1);//获取&后面的参数
            //console.log(param)
			var pid = getParams(param,"id");//获取keyde value值
            console.log(pid)
			
			//查找参数对应的值
			function getParams(str, name){
				var arr = str.split("&");
				//console.log(arr)
				for (var i=0; i<arr.length; i++) {
					var str1 = arr[i]; // id=1002
                    //console.log(str1)
					var arr1 = str1.split("=");
                    //console.log(arr1)
					if (arr1[0] == name) {
					    //console.log(arr1[0])
                        //console.log(arr1[1])
						return arr1[1];
					}
				}
				return "";
			}
			//获取json数据
			$.get("/ajax/",function(data){
				var arr = data.goodslist;
				console.log(arr);
				//for循环遍历数组
				for (var i=0;i<$(arr).size();i++) {
					var obj = arr[i];
					{#console.log($(arr).size())#}
					{#console.log(obj)#}
					if(obj.id == pid ){

						loadUI(obj);
						var a = obj;//要先用对象存起来
						//点击加入购物车
						$("#detail_list_msg a").click(function(e){
							
							
							confirm("确定加入购物车？")
							
							var obj2 = {
								"id":a.id,
								"name":a.name,
								"price":a.price,
								"brand":a.brand,
								"src":a.img7
							}//获取的json数据太大  进行简化
//							console.log(obj2);
							//将当前点击的商品数据加入购物车（cookie）
							var arr2 = $.cookie("cart") ? JSON.parse($.cookie("cart")) : [];
							
							//判断原来的购物车中是否有相同商品
							var isExist = false;
							for (var i=0; i<arr2.length; i++) {
								if (arr2[i].id == obj2.id) {
									arr2[i].num++;
									isExist = true;
									break;
								}
							}
							if (isExist ==  false) {
								obj2.num = 1;
								obj2.checked = true; //是否选中， 默认选中 
								arr2.push(obj2);
							}
							
							
							//将arr2添加到cookie中
							$.cookie("cart", JSON.stringify(arr2), {expires:30, path:"/"});
							console.log( $.cookie("cart") );
						

						})
						$("#shoppingCar,#detail_list_msg input").click(function(){
							location.href = "/shoppingCar/";
						})
					}
				}
				//封装一个加载详情页面的方法
	
			})
			
			function loadUI(obj){
                imgsrc3 = '/static/' + obj.img3
                imgsrc7 = '/static/' + obj.img7
                imgsrc8 = '/static/' + obj.img8
                imgsrc9 = '/static/' + obj.img9
                imgsrc10 = '/static/' + obj.img10
				$("#smallImg img").attr("src",imgsrc3);
				$("#bigImg").attr("src",imgsrc3);
				$("#detail_list li img").eq(0).attr("src",imgsrc7);
				$("#detail_list li img").eq(1).attr("src",imgsrc8);
				$("#detail_list li img").eq(2).attr("src",imgsrc9);
				$("#detail_list li img").eq(3).attr("src",imgsrc10);
				$("#detail_list_msg h2").html(obj.name);
				$("#detail_list_msg h3").html(obj.brand);
				$("#detail_list_msg h4").html("￥"+obj.price);
				$("#detail_list_msg a").html("加入购物车");
				
//				var aa = $("<a href='javascript:;'>加入购物车</a>");
//				$(aa).appendTo("#detail_list_msg");
				
				
				$("#detail_list li img").click(function(){
                    imgsrc3 = '/static/' + obj.img3
                    var index = $(this).index();
					$("#smallImg img").attr("src",imgsrc3);
					$("#bigImg").attr("src",imgsrc3);
					$(this).parent().addClass("active").siblings().removeClass("active");
				})
				$("#detail_list li img").eq(1).click(function(){
				    imgsrc4 = '/static/' + obj.img4
					$("#smallImg img").attr("src",imgsrc4);
					$("#bigImg").attr("src",imgsrc4);
				})
				$("#detail_list li img").eq(2).click(function(){
				    imgsrc5 = '/static/' + obj.img5
					$("#smallImg img").attr("src",imgsrc5);
					$("#bigImg").attr("src",imgsrc5);
				})
				$("#detail_list li img").eq(3).click(function(){
				    imgsrc6 = '/static/' + obj.img6
					$("#smallImg img").attr("src",imgsrc6);
					$("#bigImg").attr("src",imgsrc6);
				})
				
			}
			
			
			
		})
	</script>
	<body>
		<!--top-->
		<div id="top">
			<ul id="list1">
				<li style="margin-left: 20px;">
					{% if username %}
                    <b> 用户：{{ username }} </b>欢迎来到尚品网,<a href="{% url 'leshangwang:logout' %}">退出</a>&nbsp;|
                    {% else %}
                        欢迎来到尚品网,<a href="{% url 'leshangwang:login' %}">登陆</a>&nbsp;|
                    {% endif %}
				</li>
				<li><a href="register.html">注册</a></li>
				<li id="shoppingCar">
					<i class="iconfont">&#xe600;</i>
					购物袋(0)
					<i class="iconfont" style="font-size: 12px;">&#xe6a3;</i>
				</li>
			</ul>
		</div>
		
		<div id="logo">
			<a href="#" style="color: #000000;">女士</a>
			<a href="#">男士</a>
			<a href="#">儿童</a>
			<div class="logobox">
				<img src="{% static 'img/indexImg/logo_v100.png' %}" />
			</div>
			<div class="iconBox">
				<i class="iconfont">&#xe601;</i>
				<i class="iconfont">&#xe626;</i>
			</div>
		
		<!--放大镜-->
		<div id="magnifier">
			<div id="smallImg">
				<img src="" />
				<div id="smallArea"></div>
			</div>
			
			<div id="bigArea">
				<img id="bigImg" src="" />
			</div>
			
			
			
			<ul id="detail_list">
				<li><img src="" / ></li>
				<li><img src="" /></li>
				<li><img src="" /></li>
				<li><img src="" /></li>
			</ul>
			
			
			<div id="detail_list_msg">
				<h2 style="font-size: 30px;font-weight: 600;"></h2>
				<h3 style="font-size: 24px;font-weight: 600;"></h3>
				<h4 style="font-size: 24px;font-weight: 600;"></h4>
				<a href='javascript:;'></a>
				<input type="button" value="进入购物车" />
			</div>
		</div>
		
		
		
		
		
		
		<div id="foot">
			<div id="foot1">
				<img src="/static/img/footImg/foot1.jpg" />
			</div>
			<div id="foot2">
				<img src="/static/img/footImg/foot2.jpg" />
			</div>
			<div id="foot3">
				<img src="/static/img/footImg/foot3.jpg" />
			</div>
		</div>
	</body>
</html>

templates/html/list.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/reset .css' %}">
        <link rel="stylesheet" href="{% static 'css/list.css' %}">
        <link rel="stylesheet" href="{% static 'css/swiper-3.4.2.min.css' %}">
		<script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}" ></script>
        <script type="text/javascript" src="{% static 'js/swiper-3.4.2.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/list.js' %}" ></script>
	</head>
	<body>
		<!--top-->
		<div id="top">
			<ul id="list1">
				<li style="margin-left: 20px;">
					{% if username %}
                    <b> 用户：{{ username }} </b>欢迎来到尚品网,<a href="{% url 'leshangwang:logout' %}">退出</a>&nbsp;|
                    {% else %}
                        欢迎来到尚品网,<a href="{% url 'leshangwang:login' %}">登陆</a>&nbsp;|
                    {% endif %}
				</li>
				<li><a href="{% url 'leshangwang:register' %}">注册</a></li>
				<li>
					<i class="iconfont">&#xe600;</i>
					<a href="{% url 'leshangwang:shoppingCar' %}">购物袋(0)</a>
					<i class=" iconfont" style="font-size: 12px;">&#xe6a3;</i>
				</li>
			</ul>
		</div>
		<!--侧边栏-->
		
		<div id="sidebar">
			<ul id="sidebar_list">
				<li>
					<a href="#">
						<img src="{% static 'img/sidebarImg/2.png' %}" />
					</a>
				</li>
				<li>
					<a href="#">
						<img src="{% static 'img/sidebarImg/4.png' %}" />
					</a>
				</li>
				<li>
					<a href="#">
						<img src="{% static 'img/sidebarImg/1.png' %}" />
					</a>
				</li>
				<li class="boder">
					<a href="#">
						<img src="{% static 'img/sidebarImg/3.png' %}" />
					</a>
				</li>
			</ul>
			<div id="weixin"><img src="{% static 'img/sidebarImg/footer-weixin.png' %}" /></div>
			<div id="app"><img src="{% static 'img/sidebarImg/footer-app.png' %}" /></div>
		</div>
		
		
		<div id="logo">
			<a href="#" style="color: #000000;">女士</a>
			<a href="#">男士</a>
			<a href="#">儿童</a>
			<div class="logobox">
				<img src="{% static 'img/indexImg/logo_v100.png' %}" />
			</div>
			<div class="iconBox">
				<i class="iconfont">&#xe601;</i>
				<i class="iconfont">&#xe626;</i>
			</div>
		</div>
		
		
		<div class="nav_wrap" style="width: 960px;margin: 0 auto; height: 454px; position: relative;overflow: hidden;">
			<ul id="list2">
				<li>当季新品</li>
				<li>服装</li>
				<li>鞋靴</li>
				<li>箱包</li>
				<li>配件</li>
				<li>品牌</li>
				<li>TOPSHOP</li>
				<li style="text-align: right;">SALE</li>
			</ul>

        <!-- Swiper -->
    <div class="swiper-container" id="topSwiper">
        <div class="swiper-wrapper">
            <div class="swiper-slide"><img src="{% static 'img/navImg/1.png' %}"></div>
            <div class="swiper-slide"><img src="{% static 'img/navImg/2.png' %}"></div>
            <div class="swiper-slide"><img src="{% static 'img/navImg/3.png' %}"></div>
            <div class="swiper-slide"><img src="{% static 'img/navImg/4.png' %}"></div>
            <div class="swiper-slide"><img src="{% static 'img/navImg/5.png' %}"></div>
            <div class="swiper-slide"><img src="{% static 'img/navImg/6.png' %}"></div>
            <div class="swiper-slide"><img src="{% static 'img/navImg/7.png' %}"></div>
            <div class="swiper-slide"><img src="{% static 'img/navImg/8.png' %}"></div>
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination"></div>
        <!-- Add Arrows -->
        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
    </div>


        </div>


		<div id="shoes">
			<h2>高跟鞋</h2>
			<ul id="shoes_list">

			</ul>
		</div>
		
		<div id="foot">
			<div id="foot1">
				<img src="{% static 'img/footImg/foot1.jpg' %}" />
			</div>
			<div id="foot2">
				<img src="{% static 'img/footImg/foot2.jpg' %}" />
			</div>
			<div id="foot3">
				<img src="{% static 'img/footImg/foot3.jpg' %}" />
			</div>
		</div>
	</body>
</html>

templates/html/register.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>login</title>
		<script type="text/javascript" src="{% static 'js/ajax.js' %}" ></script>
        <link rel="stylesheet" href="{% static 'css/register.css' %}" />
		<script type="text/javascript" src="{% static 'js/register.js' %}" ></script>

	</head>
	<body>
		<div id="logo">
			<img src="{% static 'img/loginImg/logo_v100.png' %}" />
		</div>
		<form id="form_login" action="{% url 'leshangwang:register' %}" method="post">
            {% csrf_token %}
			<div class="tip">新用户注册即可领取500元专享礼包</div>
			
			<div id="form_left">
				<h4>注册新账号</h4>
				        <input type="text" placeholder="请输入用户账号或手机号" id="phone" name="username" />
				<p></p>
				
				<input type="text" placeholder="请输入图形验证码" id="checkNum"  />
				<p></p>
				<div id="box">
					<div id="yanzheng"></div>
					<div id="change">换一换</div>
				</div>
				
{#				<input type="text" placeholder="请输入短信验证码" id="msg" />#}
{#				<div id="msgNum">获取验证码</div>#}
				<p></p>
				
				<input type="password" placeholder="请设置密码" id="psd" name="password"/>
				<p class="passwordLevel"></p>
				<div id="psdLevel">
					<span>弱</span>
					<span>中</span>
					<span>强</span>
				</div>
				
				<span id="sp1"><input type="checkbox" checked="checked" />
				我以阅读并同意<a href="javascript:;"><<尚品网用户协议>></a>
				</span>
				<input type="submit" value="注册" id="btn"  />
			</div>
			
			
			<div id="form_right">
				<div id="box1">
					<p>已有尚品账号：</p>
					<a href="{% url 'leshangwang:login' %}">直接登陆</a>
					<img src="{% static 'img/loginImg/arrow.jpg' %}" />
				</div>
				<div id="box2">
					<img src="{% static 'img/loginImg/loginBg.jpg' %}" />
				</div>
			</div>
		</form>
		
	</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title></title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/reset .css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />
		<script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/index.js' %}" ></script>
		
	</head>
	<body>

		<!--top-->
		<div id="top">
			<ul id="list1">

				<li style="margin-left: 20px;">
                    {% if username %}
                    <b> 用户：{{ username }} </b>欢迎来到尚品网,<a href="{% url 'leshangwang:logout' %}">退出</a>&nbsp;|
                    {% else %}
                        欢迎来到尚品网,<a href="{% url 'leshangwang:login' %}">登陆</a>&nbsp;|
                    {% endif %}

				</li>

				<li><a href="{% url 'leshangwang:register' %}">注册</a></li>

{#                {% endif %}#}

				<li>
					<i class="iconfont">&#xe600;</i>
                    <a href="#">
                        购物袋(0)
                    </a>

					<i class="iconfont" style="font-size: 12px;">&#xe6a3;</i>
				</li>
			</ul>
		</div>
		<!--侧边栏-->
		
		<div id="sidebar">
			<ul id="sidebar_list">
				<li>
					<a href="#">
						<img src="{% static 'img/sidebarImg/2.png' %}" />
					</a>
				</li>
				<li>
					<a href="#">
						<img src="{% static 'img/sidebarImg/4.png' %}" />
					</a>
				</li>
				<li>
					<a href="#">
						<img src="{% static 'img/sidebarImg/1.png' %}" />
					</a>
				</li>
				<li class="boder">
					<a href="#">
						<img src="{% static 'img/sidebarImg/3.png' %}" />
					</a>
				</li>
			</ul>
			<div id="weixin"><img src="{% static 'img/sidebarImg/footer-weixin.png' %}" /></div>
			<div id="app"><img src="{% static 'img/sidebarImg/footer-app.png' %}" /></div>
		</div>
		
		<div id="logo">
			<a href="#" style="color: #000000;">女士</a>
			<a href="#">男士</a>
			<a href="#">儿童</a>
			<div class="logobox">
				<img src="{% static 'img/indexImg/logo_v100.png' %}" />
			</div>
			<div class="iconBox">
				<i class="iconfont">&#xe601;</i>
				<i class="iconfont">&#xe626;</i>
			</div>
		</div>
		<div class="nav_wrap" style="width: 960px;margin: 0 auto; ">
			<ul id="list2">
				<li>当季新品</li>
				<li>服装</li>
				<li>鞋靴</li>
				<li>箱包</li>
				<li>配件</li>
				<li>品牌</li>
				<li>TOPSHOP</li>
				<li style="text-align: right; color: red; font-weight: 600;">SALE</li>
			</ul>
			<div class="list2_con">
				<img src="{% static 'img/navImg/1.png' %}" />
			</div>
			<div class="list2_con">
				<img src="{% static 'img/navImg/2.png' %}" />
			</div>
			<div class="list2_con">
				<img src="{% static 'img/navImg/3.png' %}" />
			</div>
			<div class="list2_con">
				<img src="{% static 'img/navImg/4.png' %}" />
			</div>
			<div class="list2_con">
				<img src="{% static 'img/navImg/5.png' %}" />
			</div>
			<div class="list2_con">
				<img src="{% static 'img/navImg/6.png' %}" />
			</div>
			<div class="list2_con">
				<img src="{% static 'img/navImg/7.png' %}" />
			</div>
			<div class="list2_con">
				<img src="{% static 'img/navImg/8.png' %}" />
			</div>
		</div>
		
		<div id="ad">
			<img src="{% static 'img/adImg/ad1.png' %}" />
		</div>
		<div id="ad2"></div>
		<!--主要内容区-->
		
		<div id="main">
			
			<ul id="main_list1">
				<li><img src="{% static 'img/mainImg/pic1.png' %}" /></li>
				<li class="list_center"><img src="{% static 'img/mainImg/pic2.png' %}" /></li>
				<li><img src="{% static 'img/mainImg/pic3.png' %}" /></li>
			</ul>
			
			<ul id="main_list2">
				<li><img src="{% static 'img/mainImg/pic4.png' %}" /></li>
				<li style="margin-left: 20px;"><img src="{% static 'img/mainImg/pic5.png' %}" /></li>
			</ul>
		</div>
		<div id="man_ad">
			<a href="https://www.baidu.com/">
				<img src="{% static 'img/adImg/manAd.jpg' %}" />
			</a>
		</div>
		<div id="mayLike">
			<p>猜你喜欢</p>
		</div>
		<div id="carousel">
			<ul id="may_list">
				<li>
					<a href="javascript:;">
						<img src="{% static 'img/mayListImg/1.jpg' %}"/>
					</a>
					<h4>ALEXANDER</h4>
					<i >¥6800</i>
				</li>
				<li>
					<a href="javascript:;">
						<img src="{% static 'img/mayListImg/2.jpg' %}"/>
					</a>
					<h4>ALEXANDER</h4>
					<i >¥6800</i>
				</li>
				<li>
					<a href="javascript:;">
						<img src="{% static 'img/mayListImg/3.jpg' %}"/>
					</a>
					<h4>ALEXANDER</h4>
					<i >¥6800</i>
				</li>
				<li>
					<a href="javascript:;">
						<img src="{% static 'img/mayListImg/4.jpg' %}"/>
					</a>
					<h4>ALEXANDER</h4>
					<i >¥6800</i>
				</li>
				<li>
					<a href="javascript:;">
						<img src="{% static 'img/mayListImg/5.jpg' %}"/>
					</a>
					<h4>ALEXANDER</h4>
					<i >¥6800</i>
				</li>
				<li>
					<a href="javascript:;">
						<img src="{% static 'img/mayListImg/6.jpg' %}"/>
					</a>
					<h4>ALEXANDER</h4>
					<i >¥6800</i>
				</li>
				<li>
					<a href="javascript:;">
						<img src="{% static 'img/mayListImg/7.jpg' %}"/>
					</a>
					<h4>ALEXANDER</h4>
					<i >¥6800</i>
				</li>
				<li>
					<a href="javascript:;">
						<img src="{% static 'img/mayListImg/8.jpg' %}"/>
					</a>
					<h4>ALEXANDER</h4>
					<i >¥6800</i>
				</li>
				<li>
					<a href="javascript:;">
						<img src="{% static 'img/mayListImg/9.jpg' %}"/>
					</a>
					<h4>ALEXANDER</h4>
					<i >¥6800</i>
				</li>
				<li>
					<a href="javascript:;">
						<img src="{% static 'img/mayListImg/10.jpg' %}"/>
					</a>
					<h4>ALEXANDER</h4>
					<i >¥6800</i>
				</li>
				<li>
					<a href="javascript:;">
						<img src="{% static 'img/mayListImg/11.jpg' %}"/>
					</a>
					<h4>ALEXANDER</h4>
					<i >¥6800</i>
				</li>
				<li>
					<a href="javascript:;">
						<img src="{% static 'img/mayListImg/12.jpg' %}"/>
					</a>
					<h4>ALEXANDER</h4>
					<i >¥6800</i>
				</li>
				<li>
					<a href="javascript:;">
						<img src="{% static 'img/mayListImg/13.jpg' %}"/>
					</a>
					<h4>ALEXANDER</h4>
					<i >¥6800</i>
				</li>
				<li>
					<a href="javascript:;">
						<img src="{% static 'img/mayListImg/14.jpg' %}"/>
					</a>
					<h4>ALEXANDER</h4>
					<i >¥6800</i>
				</li>
				<li>
					<a href="javascript:;">
						<img src="{% static 'img/mayListImg/15.jpg' %}"/>
					</a>
					<h4>ALEXANDER</h4>
					<i >¥6800</i>
				</li>
				
			</ul>
			<div id="btn">
				<span class="next"><img src="{% static 'img/indexImg/right.png' %}"/></span>
				<span class="pre"><img src="{% static 'img/indexImg/left.png' %}"/></span>
			</div>
		</div>
		
		
		<div id="foot">
			<div id="foot1">
				<img src="{% static 'img/footImg/foot1.jpg' %}" />
			</div>
			<div id="foot2">
				<img src="{% static 'img/footImg/foot2.jpg' %}" />
			</div>
			<div id="foot3">
				<img src="{% static 'img/footImg/foot3.jpg' %}" />
			</div>
		</div>
		
	</body>
</html>